//
// Created by noa on 15/01/2020.
//

#ifndef MILESTONE_2_ADVANCED_PROGRAMMING__MYCLIENTHANDLER_H_
#define MILESTONE_2_ADVANCED_PROGRAMMING__MYCLIENTHANDLER_H_

class MyClientHandler {

};

#endif //MILESTONE_2_ADVANCED_PROGRAMMING__MYCLIENTHANDLER_H_
