//
// Created by hani on 15/01/2020.
//

#ifndef MILESTONE_2_ADVANCED_PROGRAMMING_MYSERIALSERVER_H
#define MILESTONE_2_ADVANCED_PROGRAMMING_MYSERIALSERVER_H


class MySerialServer {

};


#endif //MILESTONE_2_ADVANCED_PROGRAMMING_MYSERIALSERVER_H
