//
// Created by noa on 19/01/2020.
//

#ifndef MILESTONE_2_ADVANCED_PROGRAMMING__MYTESTCLIENTHANDLER_H_
#define MILESTONE_2_ADVANCED_PROGRAMMING__MYTESTCLIENTHANDLER_H_

class MyTestClientHandler {

};

#endif //MILESTONE_2_ADVANCED_PROGRAMMING__MYTESTCLIENTHANDLER_H_
